language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="EasyButtonAtInt01 Arduino Library"
before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
   - build_platform uno
   - build_platform leonardo
   - build_platform trinket
notifications:
  email:
    on_success: always
    on_failure: always
